# 创建命名空间  ：kubectl create namespace xuxiaowei-cloud
# 创建 pod    ：kubectl apply -f wechat-miniprogram-deployment.yaml
# 查看 pod    ：kubectl -n xuxiaowei-cloud get pod -o wide
# 查看 pod 描述：kubectl -n xuxiaowei-cloud describe pod pod名称
# 进入 pod    ：kubectl -n xuxiaowei-cloud exec -it pod名称 bash
# 编辑 pod    ：kubectl -n xuxiaowei-cloud edit deployment wechat-miniprogram-deployment
# 删除 pod    ：kubectl -n xuxiaowei-cloud delete deployment wechat-miniprogram-deployment

# https://kubernetes.io/zh-cn/docs/concepts/storage/persistent-volumes/
apiVersion: v1
kind: PersistentVolume
metadata:
  name: wechat-miniprogram-logs-volume
spec:
  capacity:
    storage: 10Gi
  # https://kubernetes.io/zh-cn/docs/concepts/storage/persistent-volumes/#access-modes
  accessModes:
    - ReadWriteMany
  # https://kubernetes.io/zh-cn/docs/concepts/storage/volumes/#nfs
  nfs:
    # NFS 文档：https://www.yuque.com/xuxiaowei-com-cn/gitlab-k8s/nfs
    # 需要存在此文件夹
    path: /nfs/wechat-miniprogram/logs
    # 填写你的 NFS（Network File System，网络文件系统） 地址
    server: 192.168.0.12

---

# https://kubernetes.io/zh-cn/docs/concepts/workloads/controllers/deployment/
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wechat-miniprogram-deployment
  namespace: xuxiaowei-cloud
spec:
  selector:
    matchLabels:
      app: wechat-miniprogram
  replicas: 2
  template:
    metadata:
      labels:
        app: wechat-miniprogram
    spec:
      containers:
        - name: wechat-miniprogram
          image: registry.docker.example.xuxiaowei.cloud/cloud.xuxiaowei/wechat-miniprogram:0.0.1-SNAPSHOT
          env:
            - name: nacos_xuxiaowei_cloud_addr
              value: nacos-service
            - name: mysql_xuxiaowei_cloud
              value: mysql-service
            - name: redis_xuxiaowei_cloud_host
              value: redis-service
            - name: sentinel_dashboard
              value: sentinel-service:22222
          ports:
            - containerPort: 2001
            - containerPort: 9006
          command:
            - "java"
          args:
            - "-jar"
            - "app.jar"
            # 正式环境
            - "--spring.profiles.active=prod"
          volumeMounts:
            # 时区
            - name: time-zone
              mountPath: /etc/localtime
            # 引用卷的名称
            - name: wechat-miniprogram-logs-volume
              # Wechat Miniprogram 日志目录
              mountPath: /logs
      # https://kubernetes.io/zh-cn/docs/concepts/storage/volumes/
      volumes:
        # 时区
        - name: time-zone
          hostPath:
            path: /etc/localtime
        - name: wechat-miniprogram-logs-volume
          nfs:
            # NFS 文档：https://www.yuque.com/xuxiaowei-com-cn/gitlab-k8s/nfs
            path: /nfs/wechat-miniprogram/logs
            server: 192.168.0.12

---

# 创建 Service（不能指定 nodePort） ：kubectl -n xuxiaowei-cloud expose deployment wechat-miniprogram-deployment --type=NodePort --name=wechat-miniprogram-service
# 编辑 Service                    ：kubectl -n xuxiaowei-cloud edit service wechat-miniprogram-service
# 删除 Service                    ：kubectl -n xuxiaowei-cloud delete service wechat-miniprogram-service
# 查看 pod、Service               ：kubectl -n xuxiaowei-cloud get pod,svc -o wide

# https://kubernetes.io/zh-cn/docs/concepts/services-networking/service/
apiVersion: v1
kind: Service
metadata:
  name: wechat-miniprogram-service
  namespace: xuxiaowei-cloud
spec:
  ports:
    - nodePort: 32001
      port: 2001
      protocol: TCP
      targetPort: 2001
  selector:
    app: wechat-miniprogram
  type: NodePort
